sudo: false
language: node_js
node_js:
  - "iojs-v1"
  - "iojs-v2"

branches:
  only:
    - master

script: "make test-ci"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
